[phases.setup]
nixPkgs = ["php", "nodejs_18", "sqlite", "phpPackages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm ci"]

[phases.build] 
cmds = ["npm run build", "touch database/database.sqlite", "chmod 664 database/database.sqlite"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"